<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DevNAS.UmoEditor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DevNAS.UmoEditor.Domain\DevNAS.UmoEditor.Domain.csproj" />
    <ProjectReference Include="..\DevNAS.UmoEditor.TestBase\DevNAS.UmoEditor.TestBase.csproj" />
  </ItemGroup>


</Project>
