<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DevNAS.UmoEditor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.5" />
    <ProjectReference Include="..\..\src\DevNAS.UmoEditor.EntityFrameworkCore\DevNAS.UmoEditor.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\DevNAS.UmoEditor.Application.Tests\DevNAS.UmoEditor.Application.Tests.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="9.3.6" />

  </ItemGroup>

</Project>
